version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamestoredb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: always
    ports:
      - "1025:1025"  # SMTP
      - "1080:1080"  # Web UI
volumes:
  postgres_data: