name: CD - Build & Push + Migrate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: gamestore
  PROJECT_PATH: ./src/TechChallenge.GameStore.WebApi/TechChallenge.GameStore.WebApi.csproj
  STARTUP_PATH: ./src/TechChallenge.GameStore.WebApi/TechChallenge.GameStore.WebApi.csproj

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR (user/password)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute Tags
        id: meta
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          IMG="${REGISTRY}/${{ env.IMAGE_NAME }}"
          echo "latest=${IMG}:latest" >> $GITHUB_OUTPUT
          echo "sha=${IMG}:sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.latest }}
            ${{ steps.meta.outputs.sha }}
          provenance: false