name: CI - Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar pacotes
        run: dotnet restore TechChallenge.GameStore.sln

      - name: Build da solução
        run: dotnet build TechChallenge.GameStore.sln --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar pacotes
        run: dotnet restore TechChallenge.GameStore.sln

      - name: Executar testes
        run: dotnet test test/TechChallenge.GameStore.Unit.Test/TechChallenge.GameStore.Unit.Test.csproj --configuration Release --logger trx
